/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-11-06 at 03:27:33 UTC 
 * Modify at your own risk.
 */

package com.appspot.backendgear_1121.gear.model;

/**
 * Collection of Greetings.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gear. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GearBackendGreetingCollection extends com.google.api.client.json.GenericJson {

  /**
   * Greeting that stores a message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GearBackendGreeting> items;

  /**
   * Greeting that stores a message.
   * @return value or {@code null} for none
   */
  public java.util.List<GearBackendGreeting> getItems() {
    return items;
  }

  /**
   * Greeting that stores a message.
   * @param items items or {@code null} for none
   */
  public GearBackendGreetingCollection setItems(java.util.List<GearBackendGreeting> items) {
    this.items = items;
    return this;
  }

  @Override
  public GearBackendGreetingCollection set(String fieldName, Object value) {
    return (GearBackendGreetingCollection) super.set(fieldName, value);
  }

  @Override
  public GearBackendGreetingCollection clone() {
    return (GearBackendGreetingCollection) super.clone();
  }

}
